# Use an official Python runtime as a parent image
FROM python:3.12-slim AS builder

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Set PATH to include Poetry's bin directory
ENV PATH="/root/.local/bin:$PATH"

# Copy poetry configuration files
COPY pyproject.toml poetry.lock* ./

# Install backend dependencies
# --no-root is used because we are copying the code later and want to manage the project itself separately
RUN poetry install --no-interaction --no-root

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application using Poetry, with reload enabled for development
CMD ["sh", "-c", "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
