"""Add password_hash

Revision ID: bbbb1111bbbb
Revises: 44a3e635690b
Create Date: 2026-03-09 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbb1111bbbb'
down_revision: Union[str, Sequence[str], None] = '44a3e635690b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default='legacy'))
    op.drop_constraint('participants_api_key_key', 'participants', type_='unique')
    op.drop_column('participants', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('api_key', sa.VARCHAR(length=255), nullable=False, server_default=''))
    op.create_unique_constraint('participants_api_key_key', 'participants', ['api_key'])
    op.drop_column('participants', 'password_hash')
    # ### end Alembic commands ###
